version: '2'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql57
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234567
            MYSQL_DATABASE: balancePlus
        networks:
            MysqlDatabase:
                ipv4_address: 10.15.0.3
networks:
    MysqlDatabase:
        ipam:
            config:
                - subnet: 10.15.0.0/16
                  gateway: 10.15.0.1
volumes:
    dbdata:

